
        <div class="row">
            <div class="col-md-12">

                <h1>Create: helpdesk ticket</h1>

                <?php
                $form = $this->form;
                $form->prepare();
                ?>

                <?php echo $this->form()->openTag($form) ?>

                    <div class="white-box"><!-- Start fieldset -->
                        <div class="white-box-rounded-corner-top"><div></div></div>
                        <div class="white-box-content">
                            <div class="white-box-title">Ticket</div>

                            <?php echo $this->adminFormElement($form->get('token')) ?>
                            <?php echo $this->adminFormElement($form->get('subject')) ?>
                            <?php echo $this->adminFormElement($form->get('issue')) ?>
                            <?php echo $this->adminFormElement($form->get('attachment')) ?>

                        </div>
                    </div><!-- End fieldset -->

                    <div class="submit-area">
                        <div class="form-element">
                            <div class="form-inputs line-up">
                                <?php
                                $form->get('save')->setAttribute('class', 'button');
                                echo $this->formElement($form->get('save'));
                                ?>
                            </div>
                        </div>
                    </div>

                <?php echo $this->form()->closeTag() ?>

            </div>
        </div>
