
        <div class="row">
            <div class="col-md-12">

                <h1>Create ticket</h1>

                <?php
                $form = $this->form;
                $form->setAttribute('class', 'form-horizontal');
                $form->prepare();
                ?>

                <?php echo $this->form()->openTag($form) ?>

                    <fieldset>
                        <legend>Ticket</legend>

                        <?php echo $this->adminFormElement($form->get('token')) ?>
                        <?php echo $this->adminFormElement($form->get('subject')) ?>
                        <?php echo $this->adminFormElement($form->get('issue')) ?>
                        <?php echo $this->adminFormElement($form->get('attachment')) ?>

                    </fieldset>

                    <div class="form-group">
                        <div class="col-md-10 col-md-offset-2">

                            <?php
                            $form->get('save')->setAttribute('class', 'btn btn-primary');
                            echo $this->formElement($form->get('save'));
                            ?>

                        </div>
                    </div>

                <?php echo $this->form()->closeTag() ?>

            </div>
        </div>
