<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title></title>
        <meta name="description" content="" />
        <meta name="keywords" content="" />
        <link rel="stylesheet" type="text/css" href="/css/admin.css" />
        <script type="text/javascript" src="/js/admin.js"></script>
    </head>

    <body class="yui-skin-sam"><?php echo $this->adminNavigation ?>

        <div class="title">Create: helpdesk ticket</div>

        <?php echo $this->messages() ?>

        </div><!-- End top area -->

        <?php
        $form = $this->form;
        $form->prepare();
        ?>

        <?php echo $this->form()->openTag($form) ?>

            <div id="stage"><!-- Start stage area -->

                <div class="white-box"><!-- Start fieldset -->
                    <div class="white-box-rounded-corner-top"><div></div></div>
                    <div class="white-box-content">
                        <div class="white-box-title">Ticket</div>

                        <?php echo $this->adminFormElement($form->get('token')) ?>
                        <?php echo $this->adminFormElement($form->get('subject')) ?>
                        <?php echo $this->adminFormElement($form->get('issue')) ?>
                        <?php echo $this->adminFormElement($form->get('attachment')) ?>

                    </div>
                </div><!-- End fieldset -->

            </div><!-- End stage area -->

            <div class="submit-area">
                <div class="form-element">
                    <div class="form-inputs line-up">
                        <?php
                        $form->get('save')->setAttribute('class', 'button');
                        echo $this->formElement($form->get('save'));
                        ?>
                    </div>
                </div>
            </div>

        <?php echo $this->form()->closeTag() ?>

    </body>
</html>
