
        <div class="row">
            <div class="col-md-12">

                <h1>Index of: Helpdesk</h1>

                <div class="actions">
                    <img src="/images/icons/add.png" alt="Add icon" />
                    <a class="link-button" href="<?php echo $this->url('helpdesk', ['action' => 'create-ticket']); ?>">Create new ticket</a>
                </div>

                <table class="table">
                    <thead>
                        <tr>
                            <th>&nbsp;</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if (count($this->paginator)) : ?>
                        <?php echo $this->partialLoop('boxspaced/cms-helpdesk-module/helpdesk/ticket-item.phtml', $this->paginator) ?>
                        <?php else : ?>
                        <tr class="odd"><td width="100%">Empty result set</td><td>&nbsp;</td></tr>
                        <?php endif; ?>
                    </tbody>
                </table>

                <?php echo $this->paginationControl(
                    $this->paginator,
                    'Sliding',
                    'boxspaced/cms-helpdesk-module/helpdesk/admin-pagination.phtml'
                ); ?>

            </div>
        </div>
