
        <div class="row">
            <div class="col-md-12">

                <h1>Helpdesk</h1>

                <div class="panel panel-default">

                    <div class="panel-heading clearfix">
                        <a class="btn btn-default pull-left" href="<?php echo $this->url('helpdesk', ['action' => 'create-ticket']); ?>">Create new ticket</a>
                    </div>

                    <table class="table">
                        <tbody>
                            <?php if (count($this->paginator)) : ?>
                            <?php echo $this->partialLoop('boxspaced/cms-helpdesk-module/helpdesk/ticket-item.phtml', $this->paginator) ?>
                            <?php else : ?>
                            <tr class="odd"><td width="100%">Empty result set</td><td>&nbsp;</td></tr>
                            <?php endif; ?>
                        </tbody>
                    </table>

                </div>

                <?php echo $this->paginationControl(
                    $this->paginator,
                    'Sliding',
                    'boxspaced/cms-core-module/partial/pagination.phtml'
                ); ?>

            </div>
        </div>
