
        <div class="row">
            <div class="col-md-12">

                <h1>View ticket</h1>

                <?php
                $form = $this->form;
                $form->setAttribute('class', 'form-horizontal');
                $form->prepare();
                ?>

                <?php echo $this->form()->openTag($form) ?>

                    <fieldset>
                        <legend>Attachments</legend>

                        <?php foreach ($this->ticket->attachments as $attachment) : ?>
                        <p><em><?php echo $this->escapeHtml($attachment->username) ?></em> attached: <a href="<?php echo $this->url('helpdesk', ['action' => 'view-attachment'], ['query' => ['fileName' => $attachment->fileName]]); ?>" target="_blank"><?php echo $this->escapeHtml($attachment->fileName) ?></a></p>
                        <?php endforeach; ?>

                    </fieldset>

                    <fieldset>
                        <legend>Ticket</legend>

                        <div class="form-element">
                            <label class="lined-up required">Subject</label>
                            <div class="form-inputs line-up">
                                <?php echo $this->escapeHtml($this->ticket->subject) ?>
                            </div>
                            <div class="clear"></div>
                        </div>

                        <div class="form-element">
                            <label class="lined-up required">Issue</label>
                            <div class="form-inputs line-up">
                                <?php echo nl2br($this->escapeHtml($this->ticket->issue)) ?>
                            </div>
                            <div class="clear"></div>
                        </div>

                        <div class="form-element">
                            <label class="lined-up required">&nbsp;</label>
                            <div class="form-inputs line-up">
                                <?php foreach ($this->ticket->comments as $comment) : ?>
                                <p class="helpdesk-comment"><em><?php echo $this->escapeHtml($comment->username) ?></em> on <em><?php echo $this->date($comment->createdAt, 'l, F j, Y') ?></em> at <em><?php echo $this->date($comment->createdAt, 'H:i') ?></em> said:<br><br>
                                <?php echo nl2br($this->escapeHtml($comment->comment)) ?></p>
                                <?php endforeach; ?>
                            </div>
                            <div class="clear"></div>
                        </div>

                        <?php echo $this->adminFormElement($form->get('token')) ?>
                        <?php echo $this->adminFormElement($form->get('comment')) ?>
                        <?php echo $this->adminFormElement($form->get('attachment')) ?>

                    </fieldset>

                    <div class="form-group">
                        <div class="col-md-10 col-md-offset-2">

                            <?php
                            $form->get('save')->setAttribute('class', 'btn btn-primary');
                            echo $this->formElement($form->get('save'));
                            ?>

                            <?php if ($this->canResolve) : ?>
                            <?php
                            $form->get('resolve')->setAttribute('class', 'btn btn-success');
                            echo $this->formElement($form->get('resolve'));
                            ?>
                            <?php endif; ?>

                        </div>
                    </div>

                <?php echo $this->form()->closeTag() ?>

            </div>
        </div>
