<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title></title>
        <meta name="description" content="" />
        <meta name="keywords" content="" />
        <link rel="stylesheet" type="text/css" href="/css/admin.css" />
        <script type="text/javascript" src="/js/admin.js"></script>
    </head>

    <body class="yui-skin-sam"><?php echo $this->adminNavigation ?>

        <div class="title">View: helpdesk ticket</div>

        <?php echo $this->messages() ?>

        </div><!-- End top area -->

        <?php
        $form = $this->form;
        $form->prepare();
        ?>

        <?php echo $this->form()->openTag($form) ?>

            <div id="stage"><!-- Start stage area -->

                <div class="white-box"><!-- Start fieldset -->
                    <div class="white-box-rounded-corner-top"><div></div></div>
                    <div class="white-box-content">
                        <div class="white-box-title">Attachments</div>
                        <?php foreach ($this->ticket->attachments as $attachment) : ?>
                        <p><em><?php echo $this->escapeHtml($attachment->username) ?></em> attached: <a href="<?php echo $this->url('helpdesk', ['action' => 'view-attachment'], ['query' => ['fileName' => $attachment->fileName]]); ?>" target="_blank"><?php echo $this->escapeHtml($attachment->fileName) ?></a></p>
                        <?php endforeach; ?>
                    </div>
                </div><!-- End fieldset -->

                <div class="white-box"><!-- Start fieldset -->
                    <div class="white-box-rounded-corner-top"><div></div></div>
                    <div class="white-box-content">
                        <div class="white-box-title">Ticket</div>

                        <div class="form-element">
                            <label class="lined-up required">Subject</label>
                            <div class="form-inputs line-up">
                                <?php echo $this->escapeHtml($this->ticket->subject) ?>
                            </div>
                            <div class="clear"></div>
                        </div>

                        <div class="form-element">
                            <label class="lined-up required">Issue</label>
                            <div class="form-inputs line-up">
                                <?php echo nl2br($this->escapeHtml($this->ticket->issue)) ?>
                            </div>
                            <div class="clear"></div>
                        </div>

                        <div class="form-element">
                            <label class="lined-up required">&nbsp;</label>
                            <div class="form-inputs line-up">
                                <?php foreach ($this->ticket->comments as $comment) : ?>
                                <p class="helpdesk-comment"><em><?php echo $this->escapeHtml($comment->username) ?></em> on <em><?php echo $this->date($comment->createdAt, 'l, F j, Y') ?></em> at <em><?php echo $this->date($comment->createdAt, 'H:i') ?></em> said:<br><br>
                                <?php echo nl2br($this->escapeHtml($comment->comment)) ?></p>
                                <?php endforeach; ?>
                            </div>
                            <div class="clear"></div>
                        </div>

                        <?php echo $this->adminFormElement($form->get('token')) ?>
                        <?php echo $this->adminFormElement($form->get('comment')) ?>
                        <?php echo $this->adminFormElement($form->get('attachment')) ?>

                    </div>
                </div><!-- End fieldset -->

            </div><!-- End stage area -->

            <div class="submit-area">
                <div class="form-element">
                    <div class="form-inputs line-up">
                        <?php
                        $form->get('save')->setAttribute('class', 'button');
                        echo $this->formElement($form->get('save')) ?>
                    </div>
                </div>
                <?php if ($this->canResolve) : ?>
                <div class="form-element">
                    <div class="form-inputs line-up">
                        <?php
                        $form->get('resolve')->setAttribute('class', 'button');
                        echo $this->formElement($form->get('resolve')) ?>
                    </div>
                </div>
                <?php endif; ?>
            </div>

        <?php echo $this->form()->closeTag() ?>

    </body>
</html>
