
        <div class="row">
            <div class="col-md-12">

                <h1>View ticket</h1>

                <?php
                $form = $this->form;
                $form->setAttribute('class', 'form-horizontal');
                $form->prepare();
                ?>

                <?php echo $this->form()->openTag($form) ?>

                    <fieldset>
                        <legend>Attachments</legend>

                        <div class="form-group">
                            <label class="col-md-2 control-label">&nbsp;</label>
                            <div class="col-md-10">
                                <?php foreach ($this->ticket->attachments as $attachment) : ?>
                                <p class="form-control-static"><em><?php echo $this->escapeHtml($attachment->username) ?></em> attached: <a href="<?php echo $this->url('helpdesk', ['action' => 'view-attachment'], ['query' => ['fileName' => $attachment->fileName]]); ?>" target="_blank"><?php echo $this->escapeHtml($attachment->fileName) ?></a></p>
                                <?php endforeach; ?>
                            </div>
                        </div>

                    </fieldset>

                    <fieldset>
                        <legend>Ticket</legend>

                        <div class="form-group">
                            <label class="col-md-2 control-label">Subject</label>
                            <div class="col-md-10">
                                <p class="form-control-static">
                                    <?php echo $this->escapeHtml($this->ticket->subject) ?>
                                </p>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-2 control-label">Issue</label>
                            <div class="col-md-10">
                                <p class="form-control-static">
                                    <?php echo nl2br($this->escapeHtml($this->ticket->issue)) ?>
                                </p>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-2 control-label">&nbsp;</label>
                            <div class="col-md-10">
                                <?php foreach ($this->ticket->comments as $comment) : ?>
                                <p class="form-control-static helpdesk-comment"><em><?php echo $this->escapeHtml($comment->username) ?></em> on <em><?php echo $this->date($comment->createdAt, 'l, F j, Y') ?></em> at <em><?php echo $this->date($comment->createdAt, 'H:i') ?></em> said:<br><br>
                                <?php echo nl2br($this->escapeHtml($comment->comment)) ?></p>
                                <?php endforeach; ?>
                            </div>
                        </div>

                        <?php echo $this->adminFormElement($form->get('token')) ?>
                        <?php echo $this->adminFormElement($form->get('comment')) ?>
                        <?php echo $this->adminFormElement($form->get('attachment')) ?>

                    </fieldset>

                    <fieldset>
                        <legend>Submit</legend>

                        <div class="form-group">
                            <div class="col-md-10 col-md-offset-2">

                                <?php
                                $form->get('save')->setAttribute('class', 'btn btn-primary');
                                echo $this->formElement($form->get('save'));
                                ?>

                                <?php if ($this->canResolve) : ?>
                                <?php
                                $form->get('resolve')->setAttribute('class', 'btn btn-success');
                                echo $this->formElement($form->get('resolve'));
                                ?>
                                <?php endif; ?>

                            </div>
                        </div>

                    </fieldset>

                <?php echo $this->form()->closeTag() ?>

            </div>
        </div>
